### ISSUE TITLE
AttributeError: module 'torch.backends' has no attribute 'mps'

### ISSUE THREAD

**Issue by nateaskoff** [prateekt/pokemon-card-recognizer#21]
Hello @prateekt ,

I am getting the following error, perhaps you can assist me?

I am trying to build a program to run in Docker. Here are the relevant files:

*Dockerfile*

```
FROM nvidia/cuda:12.2.0-base-ubuntu22.04
RUN apt-get -y update \
    && apt-get install -y software-properties-common \
    && apt-get -y update \
    && add-apt-repository universe
RUN apt-get -y update
RUN apt-get -y install python3
RUN apt-get -y install python3-pip

RUN pip3 install --upgrade pip && \
    pip3 install boto3 pokemon-card-recognizer

WORKDIR /app

COPY . /app/

CMD ["python3", "-u", "-c", "from app import main; main()"]
```

*app.py*
```
import time
import os
import sys
import json
from pathlib import Path
from common.downloader import download_files_from_s3
from common.s3_cleaner import delete_files_from_s3
from pokemon.pokemon_query_card import pokemon_query_card

def main():
    # config file path should exist in same dir as app
    config_path = 'app_config.json'

    # open json and get vars
    with open(config_path, 'r') as json_file:
        app_config = json.load(json_file)

    # set default vars and environment variables
    bucket_name = app_config["aws"]["bucket_name"]
    os.environ['AWS_ACCESS_KEY_ID'] = app_config["aws"]["api_key"]
    os.environ['AWS_SECRET_ACCESS_KEY'] = app_config["aws"]["secret_key"]
    os.environ['POKEMONTCG_IO_API_KEY'] = app_config["tcg_io"]["api_key"]

    # where files initially get downloaded from S3
    img_download_path = os.path.join(
        app_config["core"]["app_root_dir"],
        app_config["core"]["img_download_path"]
    )

    # where img files are created in order to be processed after pre-processing has completed (i.e. splitting into individual card images)
    img_pre_proc_path = os.path.join(
        app_config["core"]["app_root_dir"],
        app_config["core"]["img_pre_proc_path"]
    )

    if not os.path.exists(img_download_path):
        os.makedirs(img_download_path)

    if not os.path.exists(img_pre_proc_path):
        os.makedirs(img_pre_proc_path)

    while True:
        download_files_from_s3(
            config_path = config_path,
            download_path = img_download_path,
            bucket_name = app_config["aws"]["bucket_name"]
        )

        # get all files in download dir and loop through to detect both pokemon and mtg cards
        pre_proc_files = os.listdir(img_download_path)

        if pre_proc_files:
            for img_dl in pre_proc_files:
                img_path = os.path.join(img_download_path, img_dl)
                pokemon_query_card(
                    img_path = img_path
                )
                # temp delete img for testing
                os.remove(img_path)

        delete_files_from_s3(
            bucket_name = app_config["aws"]["bucket_name"]
        )

        print("Sleeping for 60 seconds...")
        time.sleep(60)

if __name__ == "__main__":
    main()
```

*pokemon_query_card.py*

```
from card_recognizer.api.card_recognizer import CardRecognizer, OperatingMode

def pokemon_query_card(img_path):
    recognizer = CardRecognizer(
        mode=OperatingMode.SINGLE_IMAGE,
        set_name="MASTER"
    )
    results = []
    pred_result = recognizer.exec(img_path)
    detected_card = recognizer.classifier.reference.lookup_card_prediction(
        card_prediction=pred_result[0]
    )
    results.append(detected_card)
    return results

```

Here is the error I am seeing:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/app.py", line 55, in main
    pokemon_query_card(
  File "/app/pokemon/pokemon_query_card.py", line 4, in pokemon_query_card
    recognizer = CardRecognizer(
  File "/usr/local/lib/python3.10/dist-packages/card_recognizer/api/card_recognizer.py", line 48, in __init__
    self.ocr_pipeline = ocr.basic_ocr_with_text_cleaning_pipeline(
  File "/usr/local/lib/python3.10/dist-packages/ocr_ops/instances/ocr.py", line 54, in basic_ocr_with_text_cleaning_pipeline
    ocr_pipeline = OCRPipeline(
  File "/usr/local/lib/python3.10/dist-packages/ocr_ops/framework/pipeline/ocr_pipeline.py", line 102, in __init__
    self.ocr_op: AbstractOCROp = self.__setup_ocr_op(
  File "/usr/local/lib/python3.10/dist-packages/ocr_ops/framework/pipeline/ocr_pipeline.py", line 71, in __setup_ocr_op
    return EasyOCRTextBoxOp(autosave_output_img_path=autosave_output_img_path)
  File "/usr/local/lib/python3.10/dist-packages/ocr_ops/framework/op/ocr_op.py", line 149, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/ocr_ops/framework/op/abstract_ocr_op.py", line 244, in __init__
    self.easy_ocr_reader: Optional[easyocr.Reader] = easyocr.Reader(
  File "/usr/local/lib/python3.10/dist-packages/easyocr/easyocr.py", line 75, in __init__
    elif torch.backends.mps.is_available():
AttributeError: module 'torch.backends' has no attribute 'mps'
```

**Comment by prateekt** [comment]
I'm assuming that you're running on an Apple M1 Mac since your pytorch is attempting to use the MPS backend (https://pytorch.org/docs/stable/notes/mps.html) 

I was able to replicate your error in python 3.9 and python 3.10 on a 2021 M1 Max Mac. However, the error goes away in python 3.11 which is what I currently use for development of this repository on my Mac with no problems. Can you try upgrading to python 3.11?

**Comment by nateaskoff** [comment]
Python 3.11 worked on my system, which is where I'm running it for now anyway as I've got other issues with Docker and the nvidia drivers. Thanks, this can be closed.
